package com.teamXX.fooddelivery.restaurant.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

@Entity
@Table(name = "menu_items")
public class MenuItem {

    // id is needed to uniquely identify each menu item, and it is auto generated by the database, so we use @GeneratedValue annotation with strategy of GenerationType.IDENTITY
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // name is required, so we use @Column annotation with nullable = false
    @Column(nullable = false)
    private String name;

    // description is required, so we use @Column annotation with nullable = false
    @Column(nullable = false)
    private String description;

    // price is required, so we use @Column annotation with nullable = false
    @Column(nullable = false)
    private Double price;

    // category is required, so we use @Enumerated annotation with EnumType.STRING and @Column annotation with nullable = false
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private MenuCategory category;

    // available is required, so we use @Column annotation with nullable = false and set the default value to true
    @Column(nullable = false)
    private Boolean available = true;

    // metadata is a JSON field that can store any additional information about the menu item, 
    // so we use @JdbcTypeCode annotation to specify that it is a JSON type, 
    // and we use @Column annotation with columnDefinition = "jsonb" to specify that it should be stored as a jsonb type in the database
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "jsonb")
    private Map<String, Object> metadata;

    // createdAt is needed to keep track of when the menu item was created, and it is auto generated by the database, 
    // so we use @PrePersist annotation to set the value of createdAt before the entity is persisted to the database, 
    // and we use @Column annotation with nullable = false to specify that it is required
    @Column(nullable = false)
    private LocalDateTime createdAt;

    // restaurant is the restaurant that the menu item belongs to, 
    // and we use @ManyToOne annotation to specify the relationship between MenuItem and Restaurant, 
    // with fetch = FetchType.LAZY to specify that the restaurant should be loaded lazily when it is accessed, 
    // and we use @JoinColumn annotation to specify the foreign key column name in the menu_items table, 
    // and we use @JsonIgnore annotation to prevent infinite recursion when serializing the menu item to JSON
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "restaurant_id")
    @JsonIgnore
    private Restaurant restaurant;

    // createdAt is auto generated, so we use @PrePersist annotation to set the value of createdAt before the entity is persisted to the database
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
    }

    // --- Enum ---
    public enum MenuCategory { APPETIZER, MAIN, DESSERT, DRINK }

    // --- Getters and Setters ---
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public Double getPrice() { return price; }
    public void setPrice(Double price) { this.price = price; }

    public MenuCategory getCategory() { return category; }
    public void setCategory(MenuCategory category) { this.category = category; }

    public Boolean getAvailable() { return available; }
    public void setAvailable(Boolean available) { this.available = available; }

    public Map<String, Object> getMetadata() { return metadata; }
    public void setMetadata(Map<String, Object> metadata) { this.metadata = metadata; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    public Restaurant getRestaurant() { return restaurant; }
    public void setRestaurant(Restaurant restaurant) { this.restaurant = restaurant; }
}