package com.teamXX.fooddelivery.restaurant.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

@Entity
@Table(name = "restaurants")
public class Restaurant {

    // id is needed to uniquely identify each restaurant, and it is auto generated by the database, so we use @GeneratedValue annotation with strategy of GenerationType.IDENTITY
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // name is required, so we use @Column annotation with nullable = false
    @Column(nullable = false)
    private String name;

    // email is required and unique, so we use @Column annotation with nullable = false and unique = true
    @Column(nullable = false, unique = true)
    private String email;

    // phone is required and unique, so we use @Column annotation with nullable = false and unique = true
    @Column(nullable = false, unique = true)
    private String phone;

    // cuisineType is required, so we use @Column annotation with nullable = false, and we use @Enumerated annotation to specify that it is an enum type
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private CuisineType cuisineType;

    // status is required, so we use @Column annotation with nullable = false, and we use @Enumerated annotation to specify that it is an enum type
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private RestaurantStatus status;

    // rating is required, so we use @Column annotation with nullable = false, and we set the default value to 0.0
    @Column(nullable = false)
    private Double rating = 0.0;

    // totalRatings is required, so we use @Column annotation with nullable = false, and we set the default value to 0
    @Column(nullable = false)
    private Integer totalRatings = 0;

    // details is a JSON field that can store any additional information about the restaurant, so we use @JdbcTypeCode annotation to specify that it is a JSON type, and we use @Column annotation with columnDefinition = "jsonb" to specify that it should be stored as a jsonb type in the database
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "jsonb")
    private Map<String, Object> details;

    // createdAt is needed to keep track of when the restaurant was created, and it is auto generated by the database, so we use @PrePersist annotation to set the value of createdAt before the entity is persisted to the database, and we use @Column annotation with nullable = false to specify that it is required
    @Column(nullable = false)
    private LocalDateTime createdAt;

    // menuItems is a list of MenuItem objects that belong to the restaurant,
    // and we use @OneToMany annotation to specify the relationship between Restaurant and MenuItem, 
    // with mappedBy = "restaurant" to specify that the restaurant field in the MenuItem class is the owning side of the relationship, 
    // and we use cascade = CascadeType.ALL to specify that any changes to the restaurant should be cascaded to the menu items, 
    // and we use fetch = FetchType.LAZY to specify that the menu items should be loaded lazily when they are accessed
    @OneToMany(mappedBy = "restaurant", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private List<MenuItem> menuItems;

    // createdAt is auto generated, so we use @PrePersist annotation to set the value of createdAt before the entity is persisted to the database
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
    }

    // --- Enums ---
    public enum CuisineType { EGYPTIAN, ITALIAN, CHINESE, FAST_FOOD, SEAFOOD }
    public enum RestaurantStatus { OPEN, CLOSED, SUSPENDED }

    // --- Getters and Setters ---

    //id is auto generated, so no setter for id is needed, but we can still have it for testing purposes
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    // name is required, so we have both getter and setter for it
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    // email is required and unique, so we have both getter and setter for it
    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }

    // phone is required and unique, so we have both getter and setter for it
    public String getPhone() { return phone; }
    public void setPhone(String phone) { this.phone = phone; }

    // cuisineType is required, so we have both getter and setter for it
    public CuisineType getCuisineType() { return cuisineType; }
    public void setCuisineType(CuisineType cuisineType) { this.cuisineType = cuisineType; }

    // status is required, so we have both getter and setter for it
    public RestaurantStatus getStatus() { return status; }
    public void setStatus(RestaurantStatus status) { this.status = status; }

    // rating is required, so we have both getter and setter for it
    public Double getRating() { return rating; }
    public void setRating(Double rating) { this.rating = rating; }

    // totalRatings is required, so we have both getter and setter for it
    public Integer getTotalRatings() { return totalRatings; }
    public void setTotalRatings(Integer totalRatings) { this.totalRatings = totalRatings; }

    public Map<String, Object> getDetails() { return details; }
    public void setDetails(Map<String, Object> details) { this.details = details; }

    // createdAt is auto generated, so no setter for createdAt is needed, but we can still have it for testing purposes
    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    // menuItems is a list of MenuItem objects, so we have both getter and setter for it
    public List<MenuItem> getMenuItems() { return menuItems; }
    public void setMenuItems(List<MenuItem> menuItems) { this.menuItems = menuItems; }

}
