services:
  postgres:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    container_name: fooddelivery-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fooddeliverydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "test -f /tmp/healthy"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s

  pgadmin:
    build:
      context: .
      dockerfile: pgadmin.Dockerfile
    container_name: fooddelivery-pgadmin
    ports:
      - "9090:80"
    depends_on:
      - postgres
    restart: on-failure

  order-service:
    build:
      context: ./order-service
      dockerfile: order.Dockerfile
    container_name: fooddelivery-order-service
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fooddeliverydb
    depends_on:
      postgres:
        condition: service_healthy


  checkout-service:
    build:
      context: ./checkout-service
      dockerfile: checkout.Dockerfile
    container_name: fooddelivery-checkout-service
    ports:
      - "8085:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fooddeliverydb
    depends_on:
      postgres:
        condition: service_healthy

  delivery-service:
    build:
      context: ./delivery-service
      dockerfile: delivery.Dockerfile
    container_name: fooddelivery-delivery-service
    ports:
      - "8084:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fooddeliverydb
    depends_on:
      postgres:
        condition: service_healthy

volumes:
    pgdata: