apiVersion: v1
kind: Secret
metadata:
  name: checkout-postgres-secret
  namespace: talabat
  labels:
    app: checkout-postgres
    component: database
    feature: S5-READ-DB
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_DB: dGFsYWJhdGRiLWNoZWNrb3V0
