apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: talabat
type: Opaque
data:
  jwt-secret: WDk3UThZclI1SExjM3UwN0VhNmhLMnltZjZiWDFKdG40OVRBMTJ6TnNrV2paZDlzcFZMd0d2Qm1jcDhEM1FG # Base64 encoded value of "X97Q8YrR5HLc3u07Ea6hK2ymf6bX1Jtn49TA12zNskWjZd9spVLwGvBmcp8D3QF"