apiVersion: v1
kind: Secret
metadata:
  name: order-postgres-secret
  namespace: talabat
type: Opaque
data:
  POSTGRES_USER: dXNlcg== # Base64 encoded value of "admin"
  POSTGRES_DB: dGFsYWJhdGRiLW9yZGVycw== # Base64 encoded value of "talabatdb-orders"
  POSTGRES_PASSWORD: cG9zdGdyZXM= # Base64 encoded value of "postgres"