spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # S1-INFRA owner needs to fill this
        
        # S2-INFRA owner needs to fill this
        
        # S3-INFRA — order-service route
        - id: order-service
          uri: http://order-service:8080
          predicates:
            - Path=/api/orders/**
        
        - id: delivery-service
          uri: http://delivery-service:8080
          predicates:
            - Path=/api/deliveries/**
        
        # S5-INFRA owner needs to fill this