spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # S1-INFRA owner needs to fill this

        # S2-INFRA owner needs to fill this

        # S3-INFRA owner needs to fill this

        # S4-INFRA owner needs to fill this

        - id: checkout-service
          uri: http://checkout-service:8080
          predicates:
            - Path=/api/payments/**, /api/offers/**