apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
    # S1-INFRA owner needs to fill this
    
    # S2-INFRA: restaurant-service scrape job
    - job_name: restaurant-service
      static_configs:
        - targets: ['restaurant-service.talabat.svc.cluster.local:8080']
          labels:
            service: restaurant-service
      metrics_path: /actuator/prometheus
    
    # S3-INFRA owner needs to fill this
    
    - job_name: delivery-service
      static_configs:
        - targets: ['delivery-service.talabat.svc.cluster.local:8080']
      metrics_path: /actuator/prometheus
    
    - job_name: checkout-service
      static_configs:
        - targets: ['checkout-service.talabat.svc.cluster.local:8080']
      metrics_path: /actuator/prometheus
