apiVersion: v1
kind: ConfigMap
metadata:
  name: delivery-service-configmap
  namespace: talabat
data:
  SPRING_APPLICATION_NAME: delivery-service
  SPRING_CASSANDRA_CONTACT_POINTS: cassandra:9042
  SPRING_CASSANDRA_LOCAL_DATACENTER: datacenter1
  SPRING_CASSANDRA_KEYSPACE_NAME: fooddeliveryks
  SPRING_DATASOURCE_URL: jdbc:postgresql://delivery-postgres:5432/talabatdb-deliveries
  SPRING_DATASOURCE_USERNAME: user
  SPRING_RABBITMQ_HOST: rabbitmq
  FEIGN_ORDER_SERVICE_URL: http://order-service:8080
  FEIGN_RESTAURANT_SERVICE_URL: http://restaurant-service:8080
  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATA_REDIS_PASSWORD: redispass
  SPRING_MONGODB_URI: mongodb://root:rootpass@mongo:27017/fooddeliverymongo?authSource=admin
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: guest
  SPRING_RABBITMQ_PASSWORD: guest
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: prometheus,health,info
