apiVersion: v1
kind: ConfigMap
metadata:
  name: restaurant-service-configmap
  namespace: talabat
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://restaurant-postgres:5432/talabatdb-restaurants
  SPRING_DATASOURCE_USERNAME: user
  SPRING_RABBITMQ_HOST: rabbitmq
  FEIGN_ORDER_SERVICE_URL: http://order-service:8080