apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-configmap
  namespace: talabat
data:
  SPRING_APPLICATION_NAME: user-service
  SPRING_DATASOURCE_URL: jdbc:postgresql://user-postgres:5432/talabatdb-user
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: guest
  SPRING_RABBITMQ_PASSWORD: guest
  SPRING_RABBITMQ_LISTENER_SIMPLE_ACKNOWLEDGE_MODE: auto
  SPRING_RABBITMQ_LISTENER_SIMPLE_DEFAULT_REQUEUE_REJECTED: "false"
  SPRING_RABBITMQ_LISTENER_SIMPLE_RETRY_ENABLED: "true"
  SPRING_RABBITMQ_LISTENER_SIMPLE_RETRY_INITIAL_INTERVAL: "1000"
  SPRING_RABBITMQ_LISTENER_SIMPLE_RETRY_MAX_ATTEMPTS: "3"
  FEIGN_USER_SERVICE_URL: http://user-service:8080
  FEIGN_ORDER_SERVICE_URL: http://order-service:8080
  FEIGN_CHECKOUT_SERVICE_URL: http://checkout-service:8080
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: prometheus,health,info
  LOGGING_LOKI_URL: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push

  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: always

