apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-data
  namespace: talabat
  labels:
    app: cassandra
    component: database
    feature: S4-INFRA
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
