apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: talabat
  labels:
    app: elasticsearch
    feature: S5-INFRA
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
