apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-data
  namespace: talabat
  labels:
    app: neo4j
spec:
  accessModes: 
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
