apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-postgres-data
  namespace: talabat
  labels:
    app: order-postgres
spec:
  accessModes: 
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
