apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: talabat
  labels:
    app: rabbitmq
    feature: S5-INFRA
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
