apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: talabat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway-container
          image: 05-push-pull-pray-fooddelivery-api-gateway:latest # Replace with your actual image name
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-secret
