apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
  namespace: talabat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
        - name: restaurant-service
          image: <your-registry>/restaurant-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: restaurant-service-configmap
            - secretRef:
                name: restaurant-postgres-secret
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30