package com.team05.fooddelivery.restaurant.controller;

import com.team05.fooddelivery.restaurant.dto.RestaurantRevenueDTO;
import com.team05.fooddelivery.restaurant.dto.TopRestaurantDTO;
import com.team05.fooddelivery.restaurant.model.Restaurant;
import com.team05.fooddelivery.restaurant.service.RestaurantService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api/restaurants")
public class RestaurantController {

    // The RestaurantController class is a REST controller that handles HTTP requests related to restaurant operations.
    // It uses the RestaurantService to perform business logic and interact with the database.
    private final RestaurantService restaurantService;

    public RestaurantController(RestaurantService restaurantService) {
        this.restaurantService = restaurantService;
    }

    // The create method handles POST requests to create a new restaurant.
    @PostMapping
    public ResponseEntity<Restaurant> create(@RequestBody Restaurant restaurant) {
        return ResponseEntity.ok(restaurantService.create(restaurant));
    }

    // The getById method handles GET requests to retrieve a restaurant by its ID.
    @GetMapping("/{id}")
    public ResponseEntity<Restaurant> getById(@PathVariable Long id) {
        return ResponseEntity.ok(restaurantService.getById(id));
    }

    // The getAll method handles GET requests to retrieve all restaurants.
    @GetMapping
    public ResponseEntity<List<Restaurant>> getAll() {
        return ResponseEntity.ok(restaurantService.getAll());
    }

    // The update method handles PUT requests to update an existing restaurant.
    // @PutMapping("/{id}")
    // public ResponseEntity<Restaurant> update(@PathVariable Long id, @RequestBody Restaurant restaurant) {
    //     return ResponseEntity.ok(restaurantService.update(id, restaurant));
    // }

    // The delete method handles DELETE requests to remove a restaurant by its ID.
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable Long id) {
        restaurantService.delete(id);
        return ResponseEntity.noContent().build();
    }
    @PutMapping("/{id}/status")
    public ResponseEntity<?> updateStatus(
            @PathVariable Long id,
            @RequestBody Map<String, String> body) {

        String status = body.get("status");

        restaurantService.updateRestaurantStatus(id, status);

        return ResponseEntity.ok().build();
    }

    // S2-F1: Implement search functionality in RestaurantController to allow
    // filtering by cuisine type and rating range.
    @GetMapping("/search")
    public ResponseEntity<List<Restaurant>> search(
            @RequestParam(required = false) String cuisineType,
            @RequestParam Double minRating,
            @RequestParam Double maxRating) {
        return ResponseEntity.ok(restaurantService.searchByCuisineAndRating(cuisineType, minRating, maxRating));
    }

    // S2-F2: Implement an endpoint in RestaurantController to update only specific
    // details of a restaurant,
    @PutMapping("/{id}/details")
    public ResponseEntity<Restaurant> updateDetails(@PathVariable Long id, @RequestBody Map<String, Object> details) {
        return ResponseEntity.ok(restaurantService.updateDetails(id, details));
    }

    // S2-F3: Implement an endpoint in RestaurantController to calculate the total revenue generated by a restaurant within a specified date range, 
    // using the method defined in RestaurantService.
    @GetMapping("/{id}/revenue")
    public ResponseEntity<RestaurantRevenueDTO> getRevenueSummary(
            @PathVariable Long id,
            @RequestParam String startDate,
            @RequestParam String endDate) {
        LocalDateTime start = LocalDateTime.parse(startDate + "T00:00:00");
        LocalDateTime end = LocalDateTime.parse(endDate + "T23:59:59");
        return ResponseEntity.ok(restaurantService.getRevenueSummary(id, start, end));
    }
    //S2-F5
    @GetMapping("/details/search")
    public ResponseEntity<List<Restaurant>> filterByDetail(
            @RequestParam String key,
            @RequestParam String value,
            @RequestParam(required = false) String status
    ) {
        return ResponseEntity.ok(restaurantService.filterByDetail(key, value, status));
    }
    //s2-f6
    @GetMapping("/reports/top-rated")
    public ResponseEntity<List<TopRestaurantDTO>> getTopRated(
            @RequestParam int limit
    ) {
        return ResponseEntity.ok(restaurantService.getTopRated(limit));
    }

}