apiVersion: v1
kind: Service
metadata:
  name: checkout-postgres
  namespace: talabat
  labels:
    app: checkout-postgres
    component: database
    feature: S5-READ-DB
spec:
  clusterIP: None
  selector:
    app: checkout-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-postgres-rw
  namespace: talabat
  labels:
    app: checkout-postgres
    component: database
    feature: S5-READ-DB
spec:
  type: ClusterIP
  selector:
    app: checkout-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
