server:
  port: 8080

spring:
  application:
    name: delivery-service

  datasource:
    url: jdbc:postgresql://delivery-postgres:5432/talabatdb-deliveries
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cassandra:
    contact-points: "cassandra:9042"
    local-datacenter: datacenter1
    keyspace-name: fooddeliveryks
    schema-action: create-if-not-exists
#  cassandra:
#    contact-points: cassandra
#    port: 9042
#    local-datacenter: datacenter1
#    keyspace-name: fooddeliveryks
#    schema-action: CREATE_IF_NOT_EXISTS

  data:
    redis:
      host: redis
      port: 6379
      password: redispass

  mongodb:
    uri: mongodb://root:rootpass@mongo:27017/fooddeliverymongo?authSource=admin

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: auto
        default-requeue-rejected: false
        retry:
          enabled: true
          initial-interval: 1000
          max-retries: 3
  #          max-attempts: 3

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

feign:
  order-service:
    url: http://order-service:8080
  restaurant-service:
    url: http://restaurant-service:8080

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  endpoint:
    prometheus:
      enabled: true

#spring.application.name=delivery-service
#server.port=8080
#spring.datasource.url=jdbc:postgresql://localhost:5432/fooddeliverydb
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#jwt.secret=${JWT_SECRET}
