server:
  port: 8080

spring:
  application:
    name: delivery-service

  datasource:
    url: jdbc:postgresql://postgres:5432/fooddeliverydb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cassandra:
    contact-points: "cassandra:9042"
    local-datacenter: datacenter1
    keyspace-name: fooddeliveryks
    schema-action: create-if-not-exists
#  cassandra:
#    contact-points: cassandra
#    port: 9042
#    local-datacenter: datacenter1
#    keyspace-name: fooddeliveryks
#    schema-action: CREATE_IF_NOT_EXISTS

  data:
    redis:
      host: redis
      port: 6379
      password: redispass

  mongodb:
    uri: mongodb://root:rootpass@mongo:27017/fooddeliverymongo?authSource=admin

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

#spring.application.name=delivery-service
#server.port=8080
#spring.datasource.url=jdbc:postgresql://localhost:5432/fooddeliverydb
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#jwt.secret=${JWT_SECRET}
